timeout: 1800s
steps:
# Create the projects using Deployment Manager
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ./create_projects.sh ${PROJECT_ID}
  dir: 'scripts'

# Deploy data catalog of cloud-deployment project
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone --branch=${_DCAT_DEPLOY_BRANCH_NAME} https://github.com/vwt-digital/dcat-deploy.git
    dcat-deploy/deploy_dcat_gcp.sh config/data_catalog.json ${PROJECT_ID} ${_DCAT_DEPLOY_BRANCH_NAME} $(base64 -w0 config/github_access_token.enc)

- name: 'python:3.7'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone --branch=${_DCAT_DEPLOY_BRANCH_NAME} https://github.com/vwt-digital/dcat-deploy.git
    pip3 install requests google-cloud-kms
    export GITHUB_ACCESS_TOKEN_ENCRYPTED=$(base64 -w0 config/github_access_token.enc)
    export PROJECT_ID=${PROJECT_ID}
    python3 dcat-deploy/catalog/repos/setup_github_team_repos.py config/data_catalog.json


# Create Error Reporting log sink for parent folder
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source config/setup_logging_sink.config.sh
    gcloud logging sinks describe vwt-${_DCAT_DEPLOY_BRANCH_NAME}-$(cat config/parent_folder_id.cfg)-logging-sink-error --folder=$(cat config/parent_folder_id.cfg) || gcloud logging sinks create vwt-${_DCAT_DEPLOY_BRANCH_NAME}-$(cat config/parent_folder_id.cfg)-logging-sink-error $${_ERROR_PUBSUB_TOPIC} --log-filter='severity=ERROR' --include-children --folder=$(cat config/parent_folder_id.cfg)

# Deploy publish_build_result function to every project
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ../../config/cloud_build_result_funcs.config.sh
    for pr in $(python3 ../../scripts/listprojects.py ../../config/projects.json)
    do
        gcloud functions deploy publish_build_result_func \
        --runtime=python37 \
        --entry-point=publish_build_result_func \
        --trigger-topic=$${_TOPIC_PROJECT_ID} \
        --region=$${_DEPLOYMENT_REGION} \
        --project=$${pr} \
        --set-env-vars=TOPIC_PROJECT_ID=$${_TOPIC_PROJECT_ID},TOPIC_NAME=$${_TOPIC_NAME}
    done
    wait
  dir: 'functions/publish_build_result_func'

# Set IAM permissions on G Suite group for ODH Hub
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install virtualenv
    virtualenv -p python3 venv
    source venv/bin/activate
    source config/create_cloudbuilds_group_iam.config.sh
    pip install --upgrade google-cloud google-cloud-kms google-auth google-api-python-client
    export ADMINSDK_CREDENTIALS_ENCRYPTED=$(base64 -w0 config/adminsdk_credentials.enc)
    export PROJECT_ID=${PROJECT_ID}
    python3 scripts/create_cloudbuilds_group_iam.py config/projects.json $${_USER_IMPERSONATION_EMAIL} $${_SERVICE_ACCOUNT_SCOPE} $${_GSUITE_GROUP_KEY}

# Deploy report_build_status to GitHub function
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ../../config/cloud_build_result_funcs.config.sh
    _GITHUB_ACCESS_TOKEN_ENCRYPTED=$(base64 -w0 ../../config/github_access_token.enc)
    gcloud functions deploy report_build_status_github_func \
    --runtime=python37 \
    --trigger-topic=$${_TOPIC_PROJECT_ID} \
    --region=$${_DEPLOYMENT_REGION} \
    --set-env-vars=GITHUB_ACCESS_TOKEN_ENCRYPTED=$${_GITHUB_ACCESS_TOKEN_ENCRYPTED},PROJECT_ID=${PROJECT_ID}
  dir: 'functions/report_build_status_github_func'

# Create cloud build triggers on source repo commit
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcp_access_token=$(gcloud config config-helper --format='value(credential.access_token)')
    for project_id in $(python3 scripts/listprojects.py config/projects.json)
    do
        curl -X GET -H "Authorization: Bearer ${gcp_access_token}" "https://cloudbuild.googleapis.com/v1/projects/${project_id}/triggers" > project_triggers.json
        python3 scripts/listprojecttriggers.py config/projects.json ${project_id} |
        while read -r trigger
        do
            echo "Creating trigger in ${project_id}..."
            echo ${trigger} | tee trigger.json
            existing_id=$(python3 scripts/checktriggerexists.py project_triggers.json trigger.json)

            if [ -n "${existing_id}" ]
            then
                curl -X DELETE -H "Authorization: Bearer ${gcp_access_token}" "https://cloudbuild.googleapis.com/v1/projects/${project_id}/triggers/${existing_id}"
            fi

            curl -X POST -T trigger.json -H "Authorization: Bearer ${gcp_access_token}" "https://cloudbuild.googleapis.com/v1/projects/${project_id}/triggers"
        done
    done

substitutions:
    _DCAT_DEPLOY_BRANCH_NAME: master
